###
POST http://localhost:8080/api/users
content-type: application/json

{
  "name": "test"
}

###
GET http://localhost:8000/api/users/1


###
POST http://localhost:8000/api/users
content-type: application/json

{
  "name": "test"
}


###
GET http://localhost:8000/api/users/1


